In [ ]:
# name - Vedant Mathur
#prn - 25070123120
#topic - part A data normalisation

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Product':['Laptop','Mobile', 'Tablet', 'Headphones', 'Smartwatch', 'Camera'],
    'Price': [55000,20000,30000,2000,8000,45000],
    'Units_Sold': [25,60,35,80,50,15],
    'Discount' : [10,15,12,20,18,8]
}
df = pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          60        15
2      Tablet  30000          35        12
3  Headphones   2000          80        20
4  Smartwatch   8000          50        18
5      Camera  45000          15         8

In [ ]:
df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())
print(df[['Product','Price', 'Price_MinMax']])
df

      Product  Price  Price_MinMax
0      Laptop  55000      1.000000
1      Mobile  20000      0.339623
2      Tablet  30000      0.528302
3  Headphones   2000      0.000000
4  Smartwatch   8000      0.113208
5      Camera  45000      0.811321

      Product  Price  Units_Sold  Discount  Price_MinMax
0      Laptop  55000          25        10      1.000000
1      Mobile  20000          60        15      0.339623
2      Tablet  30000          35        12      0.528302
3  Headphones   2000          80        20      0.000000
4  Smartwatch   8000          50        18      0.113208
5      Camera  45000          15         8      0.811321

In [ ]:
cols = ['Price', 'Units_Sold', 'Discount']
df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
df_norm

      Price  Units_Sold  Discount
0  1.000000    0.153846  0.166667
1  0.339623    0.692308  0.583333
2  0.528302    0.307692  0.333333
3  0.000000    1.000000  1.000000
4  0.113208    0.538462  0.833333
5  0.811321    0.000000  0.000000

In [ ]:
df['Units_Zscore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()
print(df[['Product', 'Units_Sold', 'Units_Zscore']])

      Product  Units_Sold  Units_Zscore
0      Laptop          25     -0.799885
1      Mobile          60      0.660775
2      Tablet          35     -0.382554
3  Headphones          80      1.495437
4  Smartwatch          50      0.243443
5      Camera          15     -1.217216

In [ ]:
df['Price_Decimal'] = df['Price']/100000
print(df[['Product', 'Price', 'Price_Decimal']])

      Product  Price  Price_Decimal
0      Laptop  55000           0.55
1      Mobile  20000           0.20
2      Tablet  30000           0.30
3  Headphones   2000           0.02
4  Smartwatch   8000           0.08
5      Camera  45000           0.45

In [ ]:
df['Units_Decimal'] = df['Units_Sold']/100
print(df[['Product', 'Units_Sold', 'Units_Decimal']])

In [ ]:
#Activity B -
#DATA ENCODING

In [ ]:

import pandas as pd
import numpy as np
data = {
'Order_ID':[101,102,103,104,105,106],
'Customer_Gender':['Male','Female','Female','Male','Female','Male'],
'Payment_Method':['UPI','Credit Card','Debit Card','COD','UPI','Debit Card'],
'Product_Category':['Electronics','Clothing','Home','Electronics','Beauty','Electronics'],
'City':['Pune','Mumbai','Delhi','Bangalore','Pune','Hyderabad'],
'Order_Value':[4500,2300,3200,5200,1800,4100]
}

df1 = pd.DataFrame(data)

print(df1)

   Order_ID Customer_Gender Payment_Method Product_Category       City  \
0       101            Male            UPI      Electronics       Pune
1       102          Female    Credit Card         Clothing     Mumbai
2       103          Female     Debit Card             Home      Delhi
3       104            Male            COD      Electronics  Bangalore
4       105          Female            UPI           Beauty       Pune
5       106            Male     Debit Card      Electronics  Hyderabad

   Order_Value
0         4500
1         2300
2         3200
3         5200
4         1800
5         4100

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df1['Gender_Label'] = le.fit_transform(df1['Customer_Gender'])
df1

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Gender_Label
0,101,1,UPI,Electronics,Pune,4500,1
1,102,0,Credit Card,Clothing,Mumbai,2300,0
2,103,0,Debit Card,Home,Delhi,3200,0
3,104,1,COD,Electronics,Bangalore,5200,1
4,105,0,UPI,Beauty,Pune,1800,0
5,106,1,Debit Card,Electronics,Hyderabad,4100,1

In [ ]:
df1['City_Label'] = le.fit_transform(df1['City'])
df1

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Gender_Label,City_Label
0,101,1,UPI,Electronics,Pune,4500,1,4
1,102,0,Credit Card,Clothing,Mumbai,2300,0,3
2,103,0,Debit Card,Home,Delhi,3200,0,1
3,104,1,COD,Electronics,Bangalore,5200,1,0
4,105,0,UPI,Beauty,Pune,1800,0,4
5,106,1,Debit Card,Electronics,Hyderabad,4100,1,2

In [ ]:
df1_encoded1 = pd.get_dummies(df1, columns = ['Customer_Gender'])
df1_encoded1

,Order_ID,Payment_Method,Product_Category,City,Order_Value,Gender_Label,City_Label,Customer_Gender_0,Customer_Gender_1
0,101,UPI,Electronics,Pune,4500,1,4,False,True
1,102,Credit Card,Clothing,Mumbai,2300,0,3,True,False
2,103,Debit Card,Home,Delhi,3200,0,1,True,False
3,104,COD,Electronics,Bangalore,5200,1,0,False,True
4,105,UPI,Beauty,Pune,1800,0,4,True,False
5,106,Debit Card,Electronics,Hyderabad,4100,1,2,False,True

In [ ]:
df1_encoded1 = pd.get_dummies(df1, columns = ['Payment_Method'],drop_first=True)
df1_encoded1

,Order_ID,Customer_Gender,Product_Category,City,Order_Value,Gender_Label,City_Label,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI
0,101,1,Electronics,Pune,4500,1,4,False,False,True
1,102,0,Clothing,Mumbai,2300,0,3,True,False,False
2,103,0,Home,Delhi,3200,0,1,False,True,False
3,104,1,Electronics,Bangalore,5200,1,0,False,False,False
4,105,0,Beauty,Pune,1800,0,4,False,False,True
5,106,1,Electronics,Hyderabad,4100,1,2,False,True,False

In [ ]:
import pandas as pd
df = pd.read_csv("/content/Amazon Products Dataset Expt 14.csv")